### ISSUE TITLE
Is there a reason why Plack::Middleware::ForwardedHeaders was pulled from CPAN?

### ISSUE THREAD

**Issue by moltar** [haarg/Plack-Middleware-ForwardedHeaders#1]
According to @miyagawa it was on CPAN before.

See: https://github.com/miyagawa/Catalyst-Engine-PSGI/issues/7

**Comment by haarg** [comment]
[Plack::Middleware::ReverseProxy](https://metacpan.org/pod/Plack::Middleware::ReverseProxy) already existed, so I saw little point in maintaining this module or causing confusion.  My module hadn't been on CPAN for long, so I just deleted it.  If I was in that position now I may have marked it a deprecated instead, but it's rather late to make that choice.

**Comment by moltar** [comment]
Cool, thanks for the prompt answer.
